Nova.booting((Vue, router, store) => {
    // Vue.config.devtools = true
    // Vue.component('index-nova-flexible-content', require('./components/IndexField'))
    Vue.component('detail-nova-flexible-content', require('./components/DetailField').default)
    Vue.component('detail-nova-flexible-content-group', require('./components/DetailGroup').default)
    Vue.component('form-nova-flexible-content', require('./components/FormField').default)
    Vue.component('form-nova-flexible-content-group', require('./components/FormGroup').default)
    Vue.component('flexible-drop-menu', require('./components/OriginalDropMenu').default)
    Vue.component('flexible-search-menu', require('./components/SearchMenu').default)
    Vue.component('delete-flexible-content-group-modal', require('./components/DeleteGroupModal').default)
    Vue.component('icon-arrow-down', require('./components/icons/ArrowDown').default)
    Vue.component('icon-arrow-up', require('./components/icons/ArrowUp').default)
    Vue.component('icon-plus-square', require('./components/icons/PlusSquare').default)
    Vue.component('icon-minus-square', require('./components/icons/MinusSquare').default)
})
